version: "3.7"
services:
  arduino:
    build:
      context: .
      args:
        PROJECT: $PROJECT
    image: $PROJECT:latest
    volumes:
      - ./sketches:/$PROJECT/sketches
      - ./arduino-cli.yaml:/$PROJECT/arduino-cli.yaml
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
